#!/bin/sh

zero=$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')

while read -r local_ref local_oid _remote_ref remote_oid; do
  if ! test "$local_oid" = "$zero"; then
    if test "$remote_oid" = "$zero"; then
      # New branch, examine all commits
      range="$local_oid"
    else
      # Existing branch, examine new commits
      range="$remote_oid..$local_oid"
    fi

    # Check for stæsj commit
    commit=$(git rev-list -n 1 --grep '^stæsjet$' "$range")
    if test -n "$commit"; then
      echo >&2 "Found 'stæsj' commit in $local_ref, not pushing"
      exit 1
    fi
  fi
done

exit 0
