abbr --add ls eza
abbr --ad gs git status
abbr --ad ga git add
abbr --ad gc git checkout
abbr --ad gd git diff
abbr --ad gl git log

alias pbp 'pbpaste | base64 | pbcopy'
alias pbdp 'pbpaste | base64 -d | pbcopy'

# kubectl ala Kenneth
abbr --add k kubectl
abbr --add kaf 'kubectl apply -f'
abbr --add keti 'kubectl exec -t -i'
abbr --add kcuc 'kubectl config use-context'
abbr --add kcsc 'kubectl config set-context'
abbr --add kcdc 'kubectl config delete-context'
abbr --add kccc 'kubectl config current-context'
abbr --add kcgc 'kubectl config get-contexts'
abbr --add kdel 'kubectl delete'
abbr --add kdelf 'kubectl delete -f'
abbr --add kgp 'kubectl get pods'
abbr --add kgpa 'kubectl get pods --all-namespaces'
abbr --add kgpw 'kgp --watch'
abbr --add kgpwide 'kgp -o wide'
abbr --add kep 'kubectl edit pods'
abbr --add kdp 'kubectl describe pods'
abbr --add kdelp 'kubectl delete pods'
abbr --add kgpall 'kubectl get pods --all-namespaces -o wide'
abbr --add kgpl 'kgp -l'
abbr --add kgpn 'kgp -n'
abbr --add kgs 'kubectl get svc'
abbr --add kgsa 'kubectl get svc --all-namespaces'
abbr --add kgsw 'kgs --watch'
abbr --add kgswide 'kgs -o wide'
abbr --add kes 'kubectl edit svc'
abbr --add kds 'kubectl describe svc'
abbr --add kdels 'kubectl delete svc'
abbr --add kgi 'kubectl get ingress'
abbr --add kgia 'kubectl get ingress --all-namespaces'
abbr --add kei 'kubectl edit ingress'
abbr --add kdi 'kubectl describe ingress'
abbr --add kdeli 'kubectl delete ingress'
abbr --add kgns 'kubectl get namespaces'
abbr --add kens 'kubectl edit namespace'
abbr --add kdns 'kubectl describe namespace'
abbr --add kdelns 'kubectl delete namespace'
abbr --add kcn 'kubectl config set-context --current --namespace'
abbr --add kgcm 'kubectl get configmaps'
abbr --add kgcma 'kubectl get configmaps --all-namespaces'
abbr --add kecm 'kubectl edit configmap'
abbr --add kdcm 'kubectl describe configmap'
abbr --add kdelcm 'kubectl delete configmap'
abbr --add kgsec 'kubectl get secret'
abbr --add kgseca 'kubectl get secret --all-namespaces'
abbr --add kdsec 'kubectl describe secret'
abbr --add kdelsec 'kubectl delete secret'
abbr --add kgd 'kubectl get deployment'
abbr --add kgda 'kubectl get deployment --all-namespaces'
abbr --add kgdw 'kgd --watch'
abbr --add kgdwide 'kgd -o wide'
abbr --add ked 'kubectl edit deployment'
abbr --add kdd 'kubectl describe deployment'
abbr --add kdeld 'kubectl delete deployment'
abbr --add ksd 'kubectl scale deployment'
abbr --add krsd 'kubectl rollout status deployment'
abbr --add kgrs 'kubectl get replicaset'
abbr --add kdrs 'kubectl describe replicaset'
abbr --add kers 'kubectl edit replicaset'
abbr --add krh 'kubectl rollout history'
abbr --add kru 'kubectl rollout undo'
abbr --add kgss 'kubectl get statefulset'
abbr --add kgssa 'kubectl get statefulset --all-namespaces'
abbr --add kgssw 'kgss --watch'
abbr --add kgsswide 'kgss -o wide'
abbr --add kess 'kubectl edit statefulset'
abbr --add kdss 'kubectl describe statefulset'
abbr --add kdelss 'kubectl delete statefulset'
abbr --add ksss 'kubectl scale statefulset'
abbr --add krsss 'kubectl rollout status statefulset'
abbr --add kpf "kubectl port-forward"
abbr --add kga 'kubectl get all'
abbr --add kgaa 'kubectl get all --all-namespaces'
abbr --add kl 'kubectl logs'
abbr --add kl1h 'kubectl logs --since 1h'
abbr --add kl1m 'kubectl logs --since 1m'
abbr --add kl1s 'kubectl logs --since 1s'
abbr --add klf 'kubectl logs -f'
abbr --add klfj --set-cursor 'kubectl logs -f % | jq'
abbr --add klf1h 'kubectl logs --since 1h -f'
abbr --add klf1m 'kubectl logs --since 1m -f'
abbr --add klf1s 'kubectl logs --since 1s -f'
abbr --add kcp 'kubectl cp'
abbr --add kgno 'kubectl get nodes'
abbr --add keno 'kubectl edit node'
abbr --add kdno 'kubectl describe node'
abbr --add kdelno 'kubectl delete node'
abbr --add kgpvc 'kubectl get pvc'
abbr --add kgpvca 'kubectl get pvc --all-namespaces'
abbr --add kgpvcw 'kgpvc --watch'
abbr --add kepvc 'kubectl edit pvc'
abbr --add kdpvc 'kubectl describe pvc'
abbr --add kdelpvc 'kubectl delete pvc'
abbr --add kdsa "kubectl describe sa"
abbr --add kdelsa "kubectl delete sa"
abbr --add kgds 'kubectl get daemonset'
abbr --add kgdsa 'kubectl get daemonset --all-namespaces'
abbr --add kgdsw 'kgds --watch'
abbr --add keds 'kubectl edit daemonset'
abbr --add kdds 'kubectl describe daemonset'
abbr --add kdelds 'kubectl delete daemonset'
abbr --add kgcj 'kubectl get cronjob'
abbr --add kecj 'kubectl edit cronjob'
abbr --add kdcj 'kubectl describe cronjob'
abbr --add kdelcj 'kubectl delete cronjob'
abbr --add kgj 'kubectl get job'
abbr --add kej 'kubectl edit job'
abbr --add kdj 'kubectl describe job'
abbr --add kdelj 'kubectl delete job'

abbr --add kgh 'kubectl get hostrule'
abbr --add kgha 'kubectl get hostrule --all-namespaces'
abbr --add keh 'kubectl edit hostrule'
abbr --add kdh 'kubectl describe hostrule'
abbr --add kdelh 'kubectl delete hostrule'
